# Generated by Django 5.1.4 on 2025-01-10 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todos',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
